import dotenv from "dotenv";

dotenv.config();

export const config = {
  PORT: Number(process.env.PORT),
  HOST: process.env.HOST,
  MONGO_URL: process.env.MONGO_URL,
  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  JWT_ACCESS_EXPIRES_IN: process.env.JWT_ACCESS_EXPIRES_IN,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN,
  TOKEN_PREFIX: process.env.TOKEN_PREFIX,
  HASH_PASSWORD_ROUNDS: Number(process.env.HASH_PASSWORD_ROUNDS),
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_SECRET: process.env.GOOGLE_SECRET,
  ACTION_TOKEN_FORGOT_PASSWORD_SECRET:
    process.env.ACTION_TOKEN_FORGOT_PASSWORD_SECRET,
  ACTION_TOKEN_FORGOT_PASSWORD_EXPIRES_IN:
    process.env.ACTION_TOKEN_FORGOT_PASSWORD_EXPIRES_IN,
  EMAIL_USER: process.env.EMAIL_USER,
  EMAIL_PASS: process.env.EMAIL_PASS,
};
